// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// barbac_build_id
std::string barbac_build_id();
RcppExport SEXP _barbac_barbac_build_id() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(barbac_build_id());
    return rcpp_result_gen;
END_RCPP
}
// barbac_cpp_centroid_cluster_optimized
List barbac_cpp_centroid_cluster_optimized(CharacterVector barcodes, IntegerVector counts, double max_distance, std::string method, int kmer_size, int min_shared_kmers, bool use_kmer_filter, double merge_ratio, double error_rate, bool verbose);
RcppExport SEXP _barbac_barbac_cpp_centroid_cluster_optimized(SEXP barcodesSEXP, SEXP countsSEXP, SEXP max_distanceSEXP, SEXP methodSEXP, SEXP kmer_sizeSEXP, SEXP min_shared_kmersSEXP, SEXP use_kmer_filterSEXP, SEXP merge_ratioSEXP, SEXP error_rateSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type kmer_size(kmer_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_shared_kmers(min_shared_kmersSEXP);
    Rcpp::traits::input_parameter< bool >::type use_kmer_filter(use_kmer_filterSEXP);
    Rcpp::traits::input_parameter< double >::type merge_ratio(merge_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type error_rate(error_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(barbac_cpp_centroid_cluster_optimized(barcodes, counts, max_distance, method, kmer_size, min_shared_kmers, use_kmer_filter, merge_ratio, error_rate, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_barbac_barbac_build_id", (DL_FUNC) &_barbac_barbac_build_id, 0},
    {"_barbac_barbac_cpp_centroid_cluster_optimized", (DL_FUNC) &_barbac_barbac_cpp_centroid_cluster_optimized, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_barbac(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
